services:
  pocketbase:
    build: .
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: dashwiseIsAwesome
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/app/pb_data
      - ./pb_migrations:/app/pb_migrations
    restart: unless-stopped